/**
 * Fichas dos dez dinossauros.
 *
 * São cinco categorias com dois representantes cada:
 *   mágicos, carnívoros, herbívoros, terrestres e aquáticos.
 * Adicionar uma nova criatura é só acrescentar a arte em gfx/sprites/dinos.ts
 * e uma ficha aqui.
 */

import type { EspecieId } from '../gfx/sprites/dinos';
import type { BiomaId } from '../world/biomes';
import type { CavernaId } from '../world/caveDefs';

export type Categoria = 'magico' | 'carnivoro' | 'herbivoro' | 'terrestre' | 'aquatico';

export const NOME_CATEGORIA: Record<Categoria, string> = {
  magico: 'Mágico',
  carnivoro: 'Carnívoro',
  herbivoro: 'Herbívoro',
  terrestre: 'Terrestre',
  aquatico: 'Aquático',
};

/**
 * Dificuldade de 1 a 5, mostrada em estrelas no bestiário.
 *
 * Ela não é enfeite: a tabela abaixo é a referência usada para escrever as
 * fichas — vida, dano, velocidade de corrida, percepção e paciência sobem
 * juntas, e o comportamento muda de arisco (1) para caçador incansável (5).
 */
export type Dificuldade = 1 | 2 | 3 | 4 | 5;

export const REFERENCIA_DIFICULDADE: Record<
  Dificuldade,
  { vida: number; dano: number; corrida: number; percepcao: number; paciencia: number; nota: string }
> = {
  1: { vida: 10, dano: 1, corrida: 62, percepcao: 70, paciencia: 4, nota: 'Foge de você.' },
  2: { vida: 18, dano: 2, corrida: 76, percepcao: 95, paciencia: 6, nota: 'Só revida se for incomodado.' },
  3: { vida: 26, dano: 3, corrida: 92, percepcao: 128, paciencia: 8, nota: 'Persegue de verdade.' },
  4: { vida: 36, dano: 4, corrida: 104, percepcao: 158, paciencia: 10, nota: 'Não desiste fácil.' },
  5: { vida: 46, dano: 5, corrida: 118, percepcao: 180, paciencia: 13, nota: 'Caça você até o fim do território.' },
};

/** Como a criatura se mexe — muda a animação de andar, correr e flutuar. */
export type EstiloAnim = 'passos' | 'salta' | 'rasteja' | 'ondula' | 'flutua';

/**
 * Ficha de chefe. Um chefe é um dinossauro com três coisas a mais: fases (fica
 * mais rápido e mais agressivo conforme perde vida), um ataque especial próprio
 * e uma barra de vida com nome no alto da tela.
 */
export interface FichaChefe {
  /** Aparece embaixo do nome, na barra: "Guardião da Gruta". */
  titulo: string;
  /** Quantas fases (a vida é dividida por igual entre elas). */
  fases: number;
  /** O ataque especial que ele solta de tempos em tempos. */
  especial: 'anelDeCristal' | 'chuvaDeBrasa';
  /** Segundos entre dois especiais (encurta a cada fase). */
  intervalo: number;
  /** Criatura que ele chama para ajudar a partir da segunda fase. */
  invoca?: EspecieId;
  quantosInvoca?: number;
}

export interface FichaDino {
  id: EspecieId;
  nome: string;
  categoria: Categoria;
  /** Bioma onde nasce e para onde volta. */
  bioma: BiomaId;
  /** Preenchido só nas criaturas de caverna: elas não nascem na superfície. */
  caverna?: CavernaId;
  /** Preenchido só nos chefes do décimo andar. */
  chefe?: FichaChefe;
  /** 1 (inofensivo) a 5 (mortal). */
  dificuldade: Dificuldade;
  /** Jeito de andar: muda o balanço e a cadência da animação. */
  estilo: EstiloAnim;
  /** Segundos de veneno aplicados no golpe (0 = não envenena). */
  veneno?: number;
  /** Vida em pontos (o golpe do jogador causa 3). */
  vidaMax: number;
  /** Dano no jogador, em metades de coração. */
  dano: number;
  velocidade: number;
  /** Velocidade ao fugir ou ao investir. */
  velocidadeCorrida: number;
  /** Distância em que percebe o jogador. */
  percepcao: number;
  /** Distância do próprio ataque. */
  alcance: number;
  /** Tempo entre ataques. */
  recarga: number;
  /** Distância máxima que se afasta do próprio território ao perseguir. */
  raioTerritorio: number;
  /** Segundos de perseguição antes de desistir. */
  paciencia: number;
  /** Preparação antes do golpe (telegrafado, dá tempo de reagir). */
  preparo: number;
  /** Meia largura/altura da pegada de colisão. */
  pegada: { w: number; h: number };
  /** Raio do corpo para acerto do jogador. */
  raioCorpo: number;
  /** Ataca sem provocação. */
  agressivo: boolean;
  /** Só ataca quem invade seu território (raio pequeno). */
  territorial: boolean;
  /** Foge quando é ferido. */
  medroso: boolean;
  /** Vive na água. */
  aquatico: boolean;
  /** Flutua (mágicos): ignora objetos e balança no ar. */
  flutua: boolean;
  /** Ataque à distância com orbe mágica. */
  distancia: boolean;
  /** Some e reaparece perto quando é ferido. */
  teleporta: boolean;
  /** Cor das partículas de dano. */
  corSangue: string;
  sombra: 'p' | 'm' | 'g' | 'gg';
  /** Texto do bestiário (usado na interface e no diário futuro). */
  descricao: string;
}

export const FICHAS: Record<EspecieId, FichaDino> = {
  // ------------------------------------------------------------ MÁGICOS
  luminassauro: {
    id: 'luminassauro',
    nome: 'Luminassauro',
    categoria: 'magico',
    bioma: 'magico',
    dificuldade: 4,
    estilo: 'flutua',
    vidaMax: 18,
    dano: 2,
    velocidade: 34,
    velocidadeCorrida: 58,
    percepcao: 140,
    alcance: 110,
    recarga: 2,
    raioTerritorio: 170,
    paciencia: 7,
    preparo: 0.55,
    pegada: { w: 9, h: 4 },
    raioCorpo: 11,
    agressivo: true,
    territorial: false,
    medroso: false,
    aquatico: false,
    flutua: true,
    distancia: true,
    teleporta: true,
    corSangue: '#9fe8ff',
    sombra: 'g',
    descricao: 'Cristais nas costas guardam a luz do sol e disparam orbes de energia.',
  },
  etherodonte: {
    id: 'etherodonte',
    nome: 'Etherodonte',
    categoria: 'magico',
    bioma: 'magico',
    dificuldade: 4,
    estilo: 'flutua',
    vidaMax: 14,
    dano: 2,
    velocidade: 40,
    velocidadeCorrida: 70,
    percepcao: 150,
    alcance: 120,
    recarga: 1.6,
    raioTerritorio: 190,
    paciencia: 7,
    preparo: 0.45,
    pegada: { w: 8, h: 4 },
    raioCorpo: 10,
    agressivo: true,
    territorial: false,
    medroso: false,
    aquatico: false,
    flutua: true,
    distancia: true,
    teleporta: true,
    corSangue: '#d7b4ff',
    sombra: 'm',
    descricao: 'Vive meio no nosso mundo, meio em outro. Desaparece quando é ferido.',
  },

  // ------------------------------------------------------------ CARNÍVOROS
  raptornoz: {
    id: 'raptornoz',
    nome: 'Raptornoz',
    categoria: 'carnivoro',
    bioma: 'vale',
    dificuldade: 3,
    estilo: 'salta',
    vidaMax: 12,
    dano: 2,
    velocidade: 56,
    velocidadeCorrida: 108,
    percepcao: 145,
    alcance: 20,
    recarga: 1.1,
    raioTerritorio: 230,
    paciencia: 9,
    preparo: 0.3,
    pegada: { w: 10, h: 4 },
    raioCorpo: 11,
    agressivo: true,
    territorial: false,
    medroso: false,
    aquatico: false,
    flutua: false,
    distancia: false,
    teleporta: false,
    corSangue: '#b8322f',
    sombra: 'g',
    descricao: 'Rápido e curioso. Cerca a presa antes de dar a mordida.',
  },
  dentesangue: {
    id: 'dentesangue',
    nome: 'Dentesangue',
    categoria: 'carnivoro',
    bioma: 'vale',
    dificuldade: 4,
    estilo: 'passos',
    vidaMax: 28,
    dano: 4,
    velocidade: 42,
    velocidadeCorrida: 86,
    percepcao: 165,
    alcance: 26,
    recarga: 1.7,
    raioTerritorio: 260,
    paciencia: 11,
    preparo: 0.5,
    pegada: { w: 13, h: 5 },
    raioCorpo: 14,
    agressivo: true,
    territorial: false,
    medroso: false,
    aquatico: false,
    flutua: false,
    distancia: false,
    teleporta: false,
    corSangue: '#b8322f',
    sombra: 'gg',
    descricao: 'Cada passo faz o chão tremer. Uma mordida arranca dois corações.',
  },

  // ------------------------------------------------------------ HERBÍVOROS
  folhalonga: {
    id: 'folhalonga',
    nome: 'Folhalonga',
    categoria: 'herbivoro',
    bioma: 'vale',
    dificuldade: 2,
    estilo: 'passos',
    vidaMax: 34,
    dano: 2,
    velocidade: 22,
    velocidadeCorrida: 44,
    percepcao: 95,
    alcance: 24,
    recarga: 2.4,
    raioTerritorio: 140,
    paciencia: 5,
    preparo: 0.7,
    pegada: { w: 13, h: 5 },
    raioCorpo: 15,
    agressivo: false,
    territorial: false,
    medroso: true,
    aquatico: false,
    flutua: false,
    distancia: false,
    teleporta: false,
    corSangue: '#3f8f8a',
    sombra: 'gg',
    descricao: 'Come as folhas mais altas das araucárias. Pacífico, mas enorme.',
  },
  tricornis: {
    id: 'tricornis',
    nome: 'Tricornis',
    categoria: 'herbivoro',
    bioma: 'vale',
    dificuldade: 2,
    estilo: 'passos',
    vidaMax: 24,
    dano: 3,
    velocidade: 30,
    velocidadeCorrida: 76,
    percepcao: 110,
    alcance: 22,
    recarga: 1.9,
    raioTerritorio: 170,
    paciencia: 6,
    preparo: 0.55,
    pegada: { w: 12, h: 5 },
    raioCorpo: 13,
    agressivo: false,
    territorial: false,
    medroso: true,
    aquatico: false,
    flutua: false,
    distancia: false,
    teleporta: false,
    corSangue: '#8a6238',
    sombra: 'g',
    descricao: 'Pasta em paz — até você insistir. Aí os três chifres vêm na frente.',
  },

  // ------------------------------------------------------------ TERRESTRES
  casconte: {
    id: 'casconte',
    nome: 'Casconte',
    categoria: 'terrestre',
    bioma: 'vale',
    dificuldade: 2,
    estilo: 'passos',
    vidaMax: 36,
    dano: 3,
    velocidade: 18,
    velocidadeCorrida: 40,
    percepcao: 78,
    alcance: 22,
    recarga: 1.6,
    raioTerritorio: 120,
    paciencia: 5,
    preparo: 0.6,
    pegada: { w: 13, h: 5 },
    raioCorpo: 13,
    agressivo: false,
    territorial: true,
    medroso: false,
    aquatico: false,
    flutua: false,
    distancia: false,
    teleporta: false,
    corSangue: '#8a8f9c',
    sombra: 'g',
    descricao: 'Uma fortaleza de couro e osso. Gira a cauda-martelo em quem chega perto.',
  },
  pedrapata: {
    id: 'pedrapata',
    nome: 'Pedrapata',
    categoria: 'terrestre',
    bioma: 'vale',
    dificuldade: 2,
    estilo: 'passos',
    vidaMax: 32,
    dano: 3,
    velocidade: 20,
    velocidadeCorrida: 42,
    percepcao: 82,
    alcance: 24,
    recarga: 1.7,
    raioTerritorio: 130,
    paciencia: 5,
    preparo: 0.6,
    pegada: { w: 14, h: 5 },
    raioCorpo: 14,
    agressivo: false,
    territorial: true,
    medroso: false,
    aquatico: false,
    flutua: false,
    distancia: false,
    teleporta: false,
    corSangue: '#6f7f3a',
    sombra: 'gg',
    descricao: 'As placas nas costas esquentam ao sol. Defende o seu pedaço de vale.',
  },

  // ------------------------------------------------------------ AQUÁTICOS
  nadalonga: {
    id: 'nadalonga',
    nome: 'Nadalonga',
    categoria: 'aquatico',
    bioma: 'pantano',
    dificuldade: 3,
    estilo: 'ondula',
    vidaMax: 22,
    dano: 3,
    velocidade: 40,
    velocidadeCorrida: 78,
    percepcao: 125,
    alcance: 24,
    recarga: 1.5,
    raioTerritorio: 150,
    paciencia: 8,
    preparo: 0.45,
    pegada: { w: 12, h: 4 },
    raioCorpo: 13,
    agressivo: false,
    territorial: true,
    medroso: false,
    aquatico: true,
    flutua: false,
    distancia: false,
    teleporta: false,
    corSangue: '#3a6fb0',
    sombra: 'g',
    descricao: 'Desliza pelos lagos do vale. O pescoço aparece antes do resto.',
  },
  escamarela: {
    id: 'escamarela',
    nome: 'Escamarela',
    categoria: 'aquatico',
    bioma: 'pantano',
    dificuldade: 3,
    estilo: 'ondula',
    vidaMax: 18,
    dano: 3,
    velocidade: 48,
    velocidadeCorrida: 98,
    percepcao: 140,
    alcance: 22,
    recarga: 1.2,
    raioTerritorio: 190,
    paciencia: 9,
    preparo: 0.35,
    pegada: { w: 12, h: 4 },
    raioCorpo: 12,
    agressivo: true,
    territorial: false,
    medroso: false,
    aquatico: true,
    flutua: false,
    distancia: false,
    teleporta: false,
    corSangue: '#7fa63a',
    sombra: 'g',
    descricao: 'Caçadora das águas fundas. Não entre no lago sem olhar duas vezes.',
  },

  // ============================================================ CLAREIRA ENCANTADA
  arcanoraptor: {
    id: 'arcanoraptor',
    nome: 'Arcanoraptor',
    categoria: 'magico',
    bioma: 'magico',
    dificuldade: 3,
    estilo: 'salta',
    vidaMax: 24,
    dano: 3,
    velocidade: 58,
    velocidadeCorrida: 100,
    percepcao: 135,
    alcance: 20,
    recarga: 1,
    raioTerritorio: 230,
    paciencia: 8,
    preparo: 0.28,
    pegada: { w: 10, h: 4 },
    raioCorpo: 11,
    agressivo: true,
    territorial: false,
    medroso: false,
    aquatico: false,
    flutua: false,
    distancia: false,
    teleporta: false,
    corSangue: '#7ff0e0',
    sombra: 'g',
    descricao: 'Corre em ziguezague e some por um instante a cada salto. Difícil de acertar.',
  },
  cristalossauro: {
    id: 'cristalossauro',
    nome: 'Cristalossauro',
    categoria: 'magico',
    bioma: 'magico',
    dificuldade: 4,
    estilo: 'passos',
    vidaMax: 40,
    dano: 4,
    velocidade: 26,
    velocidadeCorrida: 60,
    percepcao: 120,
    alcance: 24,
    recarga: 1.8,
    raioTerritorio: 150,
    paciencia: 7,
    preparo: 0.6,
    pegada: { w: 14, h: 5 },
    raioCorpo: 15,
    agressivo: false,
    territorial: true,
    medroso: false,
    aquatico: false,
    flutua: false,
    distancia: false,
    teleporta: false,
    corSangue: '#a8f0ff',
    sombra: 'gg',
    descricao: 'As placas das costas são cristal puro. Guarda o veio como se fosse dele.',
  },
  lumidraco: {
    id: 'lumidraco',
    nome: 'Lumidraco',
    categoria: 'magico',
    bioma: 'magico',
    dificuldade: 5,
    estilo: 'flutua',
    vidaMax: 46,
    dano: 5,
    velocidade: 46,
    velocidadeCorrida: 84,
    percepcao: 185,
    alcance: 130,
    recarga: 1.4,
    raioTerritorio: 240,
    paciencia: 13,
    preparo: 0.45,
    pegada: { w: 10, h: 4 },
    raioCorpo: 13,
    agressivo: true,
    territorial: false,
    medroso: false,
    aquatico: false,
    flutua: true,
    distancia: true,
    teleporta: true,
    corSangue: '#fff3b0',
    sombra: 'g',
    descricao: 'Voa alto, dispara luz e reaparece do outro lado. O guardião da clareira.',
  },

  // ============================================================ PÂNTANO DAS RAÍZES
  pantanossauro: {
    id: 'pantanossauro',
    nome: 'Pântanossauro',
    categoria: 'herbivoro',
    bioma: 'pantano',
    dificuldade: 2,
    estilo: 'passos',
    vidaMax: 18,
    dano: 2,
    velocidade: 20,
    velocidadeCorrida: 44,
    percepcao: 92,
    alcance: 22,
    recarga: 2,
    raioTerritorio: 130,
    paciencia: 5,
    preparo: 0.65,
    pegada: { w: 13, h: 5 },
    raioCorpo: 14,
    agressivo: false,
    territorial: false,
    medroso: true,
    aquatico: false,
    flutua: false,
    distancia: false,
    teleporta: false,
    corSangue: '#6b8f4a',
    sombra: 'gg',
    descricao: 'Passa o dia enfiado na lama comendo raiz. Só corre quando leva susto.',
  },
  crocossauro: {
    id: 'crocossauro',
    nome: 'Crocossauro',
    categoria: 'carnivoro',
    bioma: 'pantano',
    dificuldade: 3,
    estilo: 'rasteja',
    vidaMax: 26,
    dano: 3,
    velocidade: 30,
    velocidadeCorrida: 92,
    percepcao: 130,
    alcance: 24,
    recarga: 1.3,
    raioTerritorio: 200,
    paciencia: 8,
    preparo: 0.35,
    pegada: { w: 14, h: 4 },
    raioCorpo: 13,
    agressivo: true,
    territorial: false,
    medroso: false,
    aquatico: false,
    flutua: false,
    distancia: false,
    teleporta: false,
    corSangue: '#5f7d4a',
    sombra: 'g',
    descricao: 'Fica parado feito tronco na água parada — até o tronco abrir a boca.',
  },
  venomossauro: {
    id: 'venomossauro',
    nome: 'Venomossauro',
    categoria: 'carnivoro',
    bioma: 'pantano',
    dificuldade: 5,
    estilo: 'ondula',
    veneno: 5,
    vidaMax: 40,
    dano: 3,
    velocidade: 48,
    velocidadeCorrida: 112,
    percepcao: 175,
    alcance: 22,
    recarga: 1.2,
    raioTerritorio: 250,
    paciencia: 12,
    preparo: 0.3,
    pegada: { w: 11, h: 4 },
    raioCorpo: 12,
    agressivo: true,
    territorial: false,
    medroso: false,
    aquatico: false,
    flutua: false,
    distancia: false,
    teleporta: false,
    corSangue: '#b06fe8',
    sombra: 'g',
    descricao: 'O golpe machuca pouco, mas deixa veneno: a vida cai sozinha por um tempo.',
  },

  // ============================================================ FLORESTA FECHADA
  silvassauro: {
    id: 'silvassauro',
    nome: 'Silvassauro',
    categoria: 'herbivoro',
    bioma: 'floresta',
    dificuldade: 1,
    estilo: 'salta',
    vidaMax: 10,
    dano: 1,
    velocidade: 34,
    velocidadeCorrida: 62,
    percepcao: 70,
    alcance: 16,
    recarga: 2.2,
    raioTerritorio: 110,
    paciencia: 4,
    preparo: 0.5,
    pegada: { w: 8, h: 4 },
    raioCorpo: 9,
    agressivo: false,
    territorial: false,
    medroso: true,
    aquatico: false,
    flutua: false,
    distancia: false,
    teleporta: false,
    corSangue: '#93bf68',
    sombra: 'm',
    descricao: 'Do tamanho de um cachorro. Some no meio da samambaia antes de você piscar.',
  },
  espinosselva: {
    id: 'espinosselva',
    nome: 'Espinosselva',
    categoria: 'terrestre',
    bioma: 'floresta',
    dificuldade: 3,
    estilo: 'passos',
    vidaMax: 26,
    dano: 3,
    velocidade: 26,
    velocidadeCorrida: 72,
    percepcao: 118,
    alcance: 24,
    recarga: 1.7,
    raioTerritorio: 165,
    paciencia: 7,
    preparo: 0.55,
    pegada: { w: 13, h: 5 },
    raioCorpo: 13,
    agressivo: false,
    territorial: true,
    medroso: false,
    aquatico: false,
    flutua: false,
    distancia: false,
    teleporta: false,
    corSangue: '#9f8a4a',
    sombra: 'g',
    descricao: 'A vela de espinhos nas costas abre quando ele se irrita. Costuma abrir.',
  },
  feroxossauro: {
    id: 'feroxossauro',
    nome: 'Feroxossauro',
    categoria: 'carnivoro',
    bioma: 'floresta',
    dificuldade: 4,
    estilo: 'passos',
    vidaMax: 34,
    dano: 4,
    velocidade: 46,
    velocidadeCorrida: 104,
    percepcao: 160,
    alcance: 26,
    recarga: 1.5,
    raioTerritorio: 255,
    paciencia: 10,
    preparo: 0.4,
    pegada: { w: 13, h: 5 },
    raioCorpo: 14,
    agressivo: true,
    territorial: false,
    medroso: false,
    aquatico: false,
    flutua: false,
    distancia: false,
    teleporta: false,
    corSangue: '#b8322f',
    sombra: 'gg',
    descricao: 'Caça de emboscada entre os troncos. Você ouve o rugido antes de ver.',
  },

  // ============================================================ CAMPO DE LAVA
  magmossauro: {
    id: 'magmossauro',
    nome: 'Magmossauro',
    categoria: 'terrestre',
    bioma: 'vulcanico',
    dificuldade: 3,
    estilo: 'passos',
    vidaMax: 28,
    dano: 3,
    velocidade: 24,
    velocidadeCorrida: 66,
    percepcao: 125,
    alcance: 24,
    recarga: 1.6,
    raioTerritorio: 160,
    paciencia: 7,
    preparo: 0.6,
    pegada: { w: 14, h: 5 },
    raioCorpo: 14,
    agressivo: false,
    territorial: true,
    medroso: false,
    aquatico: false,
    flutua: false,
    distancia: false,
    teleporta: false,
    corSangue: '#ff6a2a',
    sombra: 'gg',
    descricao: 'Couraça de pedra com fendas em brasa. Anda devagar porque não precisa correr.',
  },
  ignissauro: {
    id: 'ignissauro',
    nome: 'Ignissauro',
    categoria: 'magico',
    bioma: 'vulcanico',
    dificuldade: 4,
    estilo: 'salta',
    vidaMax: 32,
    dano: 4,
    velocidade: 44,
    velocidadeCorrida: 102,
    percepcao: 158,
    alcance: 105,
    recarga: 1.6,
    raioTerritorio: 235,
    paciencia: 10,
    preparo: 0.5,
    pegada: { w: 10, h: 4 },
    raioCorpo: 11,
    agressivo: true,
    territorial: false,
    medroso: false,
    aquatico: false,
    flutua: false,
    distancia: true,
    teleporta: false,
    corSangue: '#ffb14a',
    sombra: 'g',
    descricao: 'Cospe uma bola de fogo e recua. Manter distância dele não adianta.',
  },
  vulcanor: {
    id: 'vulcanor',
    nome: 'Vulcanor',
    categoria: 'carnivoro',
    bioma: 'vulcanico',
    dificuldade: 5,
    estilo: 'passos',
    vidaMax: 52,
    dano: 5,
    velocidade: 34,
    velocidadeCorrida: 92,
    percepcao: 180,
    alcance: 30,
    recarga: 1.6,
    raioTerritorio: 270,
    paciencia: 13,
    preparo: 0.55,
    pegada: { w: 15, h: 5 },
    raioCorpo: 16,
    agressivo: true,
    territorial: false,
    medroso: false,
    aquatico: false,
    flutua: false,
    distancia: false,
    teleporta: false,
    corSangue: '#ff4a1a',
    sombra: 'gg',
    descricao: 'O maior bicho do campo de lava. Cada passo dele levanta cinza do chão.',
  },

  // ============================================================ DESERTO DE VIDRO
  arenossauro: {
    id: 'arenossauro',
    nome: 'Arenossauro',
    categoria: 'herbivoro',
    bioma: 'deserto',
    dificuldade: 2,
    estilo: 'salta',
    vidaMax: 14,
    dano: 2,
    velocidade: 44,
    velocidadeCorrida: 78,
    percepcao: 96,
    alcance: 18,
    recarga: 1.4,
    raioTerritorio: 150,
    paciencia: 6,
    preparo: 0.5,
    pegada: { w: 9, h: 4 },
    raioCorpo: 10,
    agressivo: false,
    territorial: false,
    medroso: true,
    aquatico: false,
    flutua: false,
    distancia: false,
    teleporta: false,
    corSangue: '#e8c88a',
    sombra: 'm',
    descricao: 'Leve e nervoso. Corre em disparada e abre a cauda em leque para assustar.',
  },
  dunassauro: {
    id: 'dunassauro',
    nome: 'Dunassauro',
    categoria: 'terrestre',
    bioma: 'deserto',
    dificuldade: 3,
    estilo: 'passos',
    vidaMax: 28,
    dano: 3,
    velocidade: 28,
    velocidadeCorrida: 74,
    percepcao: 122,
    alcance: 24,
    recarga: 1.8,
    raioTerritorio: 165,
    paciencia: 7,
    preparo: 0.6,
    pegada: { w: 14, h: 5 },
    raioCorpo: 14,
    agressivo: false,
    territorial: true,
    medroso: false,
    aquatico: false,
    flutua: false,
    distancia: false,
    teleporta: false,
    corSangue: '#d8b06a',
    sombra: 'gg',
    descricao: 'A corcunda guarda água para semanas. O chifre serve para o resto.',
  },
  tempestossauro: {
    id: 'tempestossauro',
    nome: 'Tempestossauro',
    categoria: 'carnivoro',
    bioma: 'deserto',
    dificuldade: 5,
    estilo: 'ondula',
    vidaMax: 44,
    dano: 5,
    velocidade: 50,
    velocidadeCorrida: 118,
    percepcao: 182,
    alcance: 24,
    recarga: 1.1,
    raioTerritorio: 265,
    paciencia: 13,
    preparo: 0.3,
    pegada: { w: 11, h: 4 },
    raioCorpo: 12,
    agressivo: true,
    territorial: false,
    medroso: false,
    aquatico: false,
    flutua: false,
    distancia: false,
    teleporta: false,
    corSangue: '#c0cadf',
    sombra: 'g',
    descricao: 'Vem junto com a areia levantada. Quando você enxerga, ele já está perto.',
  },

  // ============================================================ CAVERNAS
  pedrolito: {
    id: 'pedrolito',
    nome: 'Pedrolito',
    categoria: 'herbivoro',
    bioma: 'vale',
    caverna: 'gruta',
    dificuldade: 1,
    estilo: 'salta',
    vidaMax: 10,
    dano: 1,
    velocidade: 36,
    velocidadeCorrida: 64,
    percepcao: 72,
    alcance: 16,
    recarga: 2,
    raioTerritorio: 120,
    paciencia: 4,
    preparo: 0.5,
    pegada: { w: 8, h: 4 },
    raioCorpo: 9,
    agressivo: false,
    territorial: false,
    medroso: true,
    aquatico: false,
    flutua: false,
    distancia: false,
    teleporta: false,
    corSangue: '#8f8880',
    sombra: 'm',
    descricao: 'Rói pedra o dia inteiro e sai correndo de qualquer barulho.',
  },
  cavernossauro: {
    id: 'cavernossauro',
    nome: 'Cavernossauro',
    categoria: 'terrestre',
    bioma: 'vale',
    caverna: 'gruta',
    dificuldade: 2,
    estilo: 'rasteja',
    vidaMax: 18,
    dano: 2,
    velocidade: 26,
    velocidadeCorrida: 76,
    percepcao: 96,
    alcance: 22,
    recarga: 1.7,
    raioTerritorio: 150,
    paciencia: 6,
    preparo: 0.5,
    pegada: { w: 12, h: 4 },
    raioCorpo: 12,
    agressivo: false,
    territorial: true,
    medroso: false,
    aquatico: false,
    flutua: false,
    distancia: false,
    teleporta: false,
    corSangue: '#d8d2c2',
    sombra: 'g',
    descricao: 'Nasceu no escuro e nunca viu o sol. Cava galeria atrás de galeria.',
  },
  geodonte: {
    id: 'geodonte',
    nome: 'Geodonte',
    categoria: 'terrestre',
    bioma: 'vale',
    caverna: 'gruta',
    dificuldade: 3,
    estilo: 'passos',
    vidaMax: 26,
    dano: 3,
    velocidade: 24,
    velocidadeCorrida: 70,
    percepcao: 122,
    alcance: 24,
    recarga: 1.6,
    raioTerritorio: 160,
    paciencia: 7,
    preparo: 0.55,
    pegada: { w: 14, h: 5 },
    raioCorpo: 14,
    agressivo: false,
    territorial: true,
    medroso: false,
    aquatico: false,
    flutua: false,
    distancia: false,
    teleporta: false,
    corSangue: '#c07fff',
    sombra: 'gg',
    descricao: 'As costas dele são um geodo aberto. Defende o veio como se fosse ninho.',
  },
  espectrossauro: {
    id: 'espectrossauro',
    nome: 'Espectrossauro',
    categoria: 'magico',
    bioma: 'vale',
    caverna: 'gruta',
    dificuldade: 4,
    estilo: 'flutua',
    vidaMax: 30,
    dano: 4,
    velocidade: 44,
    velocidadeCorrida: 86,
    percepcao: 165,
    alcance: 118,
    recarga: 1.5,
    raioTerritorio: 230,
    paciencia: 10,
    preparo: 0.45,
    pegada: { w: 9, h: 4 },
    raioCorpo: 11,
    agressivo: true,
    territorial: false,
    medroso: false,
    aquatico: false,
    flutua: true,
    distancia: true,
    teleporta: true,
    corSangue: '#c4d0e4',
    sombra: 'm',
    descricao: 'Some na escuridão entre um disparo e outro. Você ouve antes de ver.',
  },
  escaldossauro: {
    id: 'escaldossauro',
    nome: 'Escaldossauro',
    categoria: 'terrestre',
    bioma: 'vulcanico',
    caverna: 'mina',
    dificuldade: 3,
    estilo: 'passos',
    vidaMax: 28,
    dano: 3,
    velocidade: 26,
    velocidadeCorrida: 74,
    percepcao: 128,
    alcance: 24,
    recarga: 1.5,
    raioTerritorio: 165,
    paciencia: 7,
    preparo: 0.5,
    pegada: { w: 14, h: 5 },
    raioCorpo: 14,
    agressivo: true,
    territorial: false,
    medroso: false,
    aquatico: false,
    flutua: false,
    distancia: false,
    teleporta: false,
    corSangue: '#ff7a2a',
    sombra: 'gg',
    descricao: 'A crosta racha quando ele corre e mostra o vermelho de dentro.',
  },
  brasadonte: {
    id: 'brasadonte',
    nome: 'Brasadonte',
    categoria: 'magico',
    bioma: 'vulcanico',
    caverna: 'mina',
    dificuldade: 4,
    estilo: 'salta',
    vidaMax: 32,
    dano: 4,
    velocidade: 46,
    velocidadeCorrida: 100,
    percepcao: 158,
    alcance: 108,
    recarga: 1.5,
    raioTerritorio: 235,
    paciencia: 10,
    preparo: 0.45,
    pegada: { w: 10, h: 4 },
    raioCorpo: 11,
    agressivo: true,
    territorial: false,
    medroso: false,
    aquatico: false,
    flutua: false,
    distancia: true,
    teleporta: false,
    corSangue: '#ffb14a',
    sombra: 'g',
    descricao: 'Cospe brasa e recua dois passos. Faz isso a noite inteira.',
  },

  // ============================================================ CHEFES
  cristalodonte: {
    id: 'cristalodonte',
    nome: 'Cristalodonte',
    categoria: 'magico',
    bioma: 'vale',
    caverna: 'gruta',
    dificuldade: 5,
    estilo: 'passos',
    chefe: {
      titulo: 'Guardião da Gruta',
      fases: 3,
      especial: 'anelDeCristal',
      intervalo: 6,
      invoca: 'geodonte',
      quantosInvoca: 2,
    },
    vidaMax: 110,
    dano: 4,
    velocidade: 30,
    velocidadeCorrida: 78,
    percepcao: 340,
    alcance: 30,
    recarga: 1.5,
    raioTerritorio: 400,
    paciencia: 999,
    preparo: 0.6,
    pegada: { w: 22, h: 7 },
    raioCorpo: 22,
    agressivo: true,
    territorial: false,
    medroso: false,
    aquatico: false,
    flutua: false,
    distancia: false,
    teleporta: false,
    corSangue: '#8fe8ff',
    sombra: 'gg',
    descricao: 'A montanha de cristal que anda. Guarda o coração da gruta há muito tempo.',
  },
  ignivoro: {
    id: 'ignivoro',
    nome: 'Ignívoro',
    categoria: 'carnivoro',
    bioma: 'vulcanico',
    caverna: 'mina',
    dificuldade: 5,
    estilo: 'passos',
    chefe: {
      titulo: 'Coração do Abismo',
      fases: 3,
      especial: 'chuvaDeBrasa',
      intervalo: 5.5,
      invoca: 'escaldossauro',
      quantosInvoca: 2,
    },
    vidaMax: 120,
    dano: 5,
    velocidade: 36,
    velocidadeCorrida: 96,
    percepcao: 340,
    alcance: 32,
    recarga: 1.3,
    raioTerritorio: 400,
    paciencia: 999,
    preparo: 0.5,
    pegada: { w: 22, h: 7 },
    raioCorpo: 22,
    agressivo: true,
    territorial: false,
    medroso: false,
    aquatico: false,
    flutua: false,
    distancia: false,
    teleporta: false,
    corSangue: '#ff4a12',
    sombra: 'gg',
    descricao: 'Não é lava e não é bicho: é o Abismo levantando e vindo para cima de você.',
  },
};

export const TODAS_FICHAS: FichaDino[] = Object.values(FICHAS);

/** Fichas de um bioma da superfície, na ordem em que aparecem no bestiário. */
export function fichasDoBioma(bioma: BiomaId): FichaDino[] {
  return TODAS_FICHAS.filter((f) => !f.caverna && f.bioma === bioma);
}

/** Fichas de uma caverna, dos bichos rasos ao chefe. */
export function fichasDaCaverna(caverna: CavernaId): FichaDino[] {
  return TODAS_FICHAS.filter((f) => f.caverna === caverna);
}

/** As criaturas que nascem ao ar livre (as de caverna ficam de fora). */
export const FICHAS_SUPERFICIE: FichaDino[] = TODAS_FICHAS.filter((f) => !f.caverna);

/** Marcadores cheios/vazios da dificuldade, para a interface. */
export function estrelasDificuldade(d: Dificuldade): string {
  return '\u25cf'.repeat(d) + '\u25cb'.repeat(5 - d);
}
